= Hub Controller Rest

This application is part of the Cloud Native Robots Hackathon infrastructure. It routes the REST requests from 3Scale to the specific robot.


It exposes a RESTful API under /api/robots and extracts the token from each request as query parameter *user_key*, looks up the Robot IP in the configmap *robot-mapping-configmap* in JSON format and resends the request to the specific Robot IP.

You can modify the prefilled configmap under templates/robotmapping-configmap.yaml


IMPORTANT: This only works when the Robots are connected via OpenVPN to the OpenShift cluster. 

IMPORTANT: The application requires Java 8 JDK or greater and Maven 3.3.x or greater.

== Deploying the Application to an OpenShift Cluster 

----
$ oc login ...

$ oc new-project hubcontroller-rest

$ mvn clean fabric8:deploy -Popenshift -DskipTests
----

Just run the last command again to update to a new version.

When modifying the configmap in OpenShift, make sure to redeploy the application from the OpenSHift Console

TIP: When troubleshooting connection issues check out the the logfile of the Pod in in the OpenShift Console


