metadata:
  annotations:
    configmap.fabric8.io/update-on-change: MAP
spec:
  replicas: 1
  template:
    spec:            
      volumes:
        - name: cacerts-volume
          configMap:               
            name: cacerts
      containers:
        - volumeMounts:
          - name: cacerts-volume
            mountPath: /deployment/config
          env:
            - name: JAVA_OPTIONS
              value: "-Djavax.net.ssl.trustStore=/deployment/config/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
            - name: MAP
              valueFrom:
                configMapKeyRef:
                  key: MAP
                  name: robot-mapping-configmap
        